# This pubspec is currently mainly used to make it easier to develop by making 
# it a package.
name: testing
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: ^3.5.0

resolution: workspace

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependency:
  lints: any
