name: dart_data_home
version: 0.1.0-wip
description: >-
  A package providing a standardized way to access a user-specific data
  directory for Dart and Flutter tooling, defaulting to OS-conventions
  and configurable via the `DART_DATA_HOME` environment variable.

# This package will be published at some point to be able to use it for Dart and
# Flutter tooling that does not live in the Dart SDK.

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  cli_util: 0.5.0-wip

# We use 'any' version constraints here as we get our package versions from
# the dart-lang/sdk repo's DEPS file. Note that this is a special case; the
# best practice for packages is to specify their compatible version ranges.
# See also https://dart.dev/tools/pub/dependencies.
dev_dependencies:
  path: any
  test: any
