name: macros
version: 0.1.0
description: >-
  This package is for macro authors, and exposes the APIs necessary to write
  a macro. It exports the APIs from the `dart:_macros` library, but enables
  versioning separate from the SDK itself.
repository: https://github.com/dart-lang/sdk/tree/main/pkg/macros

environment:
  # Restrict the upper bound to the next release, which allows us to do breaking
  # changes if required, in minor SDK releases.
  sdk: ">=3.4.0-0 <3.5.0"
