name: observatory
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  args: any
  browser_launcher: any
  logging: any
  stack_trace: any
  web: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any

executables:
  observatory:
