name: analysis_server_plugin
description: A framework and support code for building plugins for the analysis server.
version: 0.1.0-dev
repository: https://github.com/dart-lang/sdk/tree/main/pkg/analysis_server_plugin

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  analyzer: ^7.3.0
  analyzer_plugin: ^0.13.0
  meta: ^1.16.0
  yaml: ^3.1.0
  yaml_edit: ^2.2.0

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  async: any
  lints: any
  test_reflective_loader: any
  test: any

