name: dynamic_modules
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: ^3.5.0

resolution: workspace

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  args: any
  expect: any
  front_end: any
  kernel: any
  lints: any
  vm: any
