name: _macros
version: 0.0.1
description: >-
  This is a private SDK vendored package, which is re-exported by the public
  `macros` package, which is a pub package. Every change to this package is
  treated as a release, see CONTRIBUTING.md for full instructions.
publish_to: none
repository: https://github.com/dart-lang/sdk/tree/main/pkg/_macros

environment:
  sdk: ^3.3.0
